version: '3'
services:
  tarin:
    image: rahamshaik/phonepaytrain:v1
    ports:
      - "81:80"
    deploy:
      replicas: 3

  movie:
    image: rahamshaik/phonepaymovie:v1
    ports:
      - "82:80"
    deploy:
      replicas: 3
      
  recharge:
    image: rahamshaik/phonepayrecharge:v1
    ports:
      - "83:80"
    deploy:
      replicas: 3
